title: Vũ Ngọc Thiện
logo: /assets/img/logo.png
description: Code dạo
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme